### ISSUE TITLE
Issue when installing on Linux (on DigitalOcean)

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/cli#76]
After a fresh install of node on DigitalOcean I can't install the `mesg-cli`

```
root@marketplace-service:~# npm i -g mesg-cli
/usr/bin/mesg-cli -> /usr/lib/node_modules/mesg-cli/bin/run

> secp256k1@3.7.1 install /usr/lib/node_modules/mesg-cli/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

npm ERR! path /root/.npm/_logs
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall scandir
npm ERR! Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!  { [Error: EACCES: permission denied, scandir '/root/.npm/_logs']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'scandir',
npm ERR!   path: '/root/.npm/_logs' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
glob error { [Error: EACCES: permission denied, scandir '/root/.npm/_logs']
  stack:
   'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }

> secp256k1@3.7.1 rebuild /usr/lib/node_modules/mesg-cli/node_modules/secp256k1
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.16.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/mesg-cli/node_modules/secp256k1/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/mesg-cli/node_modules/secp256k1/.node-gyp'
gyp ERR! System Linux 4.15.0-46-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/mesg-cli/node_modules/secp256k1
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.7.1 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@3.7.1 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Secp256k1 bindings compilation fail. Pure JS implementation will be used.

> ursa-optional@0.9.10 install /usr/lib/node_modules/mesg-cli/node_modules/ursa-optional
> node rebuild.js

ursaNative bindings compilation fail. This is not an issue. Modules that depend on it will use fallbacks.
fs.js:114
    throw err;
    ^

Error: EACCES: permission denied, open './stdout.log'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at Object.<anonymous> (/usr/lib/node_modules/mesg-cli/node_modules/ursa-optional/rebuild.js:13:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa-optional@0.9.10 install: `node rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa-optional@0.9.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-16T13_32_15_041Z-debug.log
```

**Comment by NicolasMahe** [comment]
@krhubert did you install the CLI on your Linux?

**Comment by NicolasMahe** [comment]
On ubuntu 18.04 with node 8 and npm 3.5.2, it install but when starting the cli, i get the following error:
```
root@ubuntu-s-1vcpu-1gb-sgp1-01-testnico:~# mesg-cli
(node:9258) Error Plugin: mesg-cli: files attribute must be specified in /usr/local/lib/node_modules/mesg-cli/package.json
module: @oclif/config@1.13.0
plugin: mesg-cli
root: /usr/local/lib/node_modules/mesg-cli
See more details with DEBUG=*
(node:9258) Error Plugin: @oclif/plugin-not-found: files attribute must be specified in /usr/local/lib/node_modules/mesg-cli/node_modules/@oclif/plugin-not-found/package.json
module: @oclif/config@1.13.0
plugin: @oclif/plugin-not-found
root: /usr/local/lib/node_modules/mesg-cli/node_modules/@oclif/plugin-not-found
See more details with DEBUG=*
(node:9258) Error Plugin: @oclif/plugin-help: files attribute must be specified in /usr/local/lib/node_modules/mesg-cli/node_modules/@oclif/plugin-help/package.json
module: @oclif/config@1.13.0
plugin: @oclif/plugin-help
root: /usr/local/lib/node_modules/mesg-cli/node_modules/@oclif/plugin-help
See more details with DEBUG=*
MESG CLI

VERSION
  mesg-cli/1.0.4 linux-x64 node-v8.10.0

USAGE
  $ mesg-cli [COMMAND]

COMMANDS
  account      Manage your MESG Accounts
  daemon       Manage MESG Engine
  help         display help for mesg-cli
  marketplace  Let you interact with the MESG Marketplace
  service      Manage MESG Services
```

**Comment by NicolasMahe** [comment]
I got the same error that Anthony with any version of node >= 10

**Comment by krhubert** [comment]
> @krhubert did you install the CLI on your Linux?

@NicolasMahe 

No, I've been using github repo, because there was no npm package at that time.

And about cli, I was able to install it with yarn  :)
(I always had a pbm with installing blockchain/crypto packages with npm).

Note: there is a common problem with npm opening too many files on linux - try to increase ulimits (https://www.imakewebsites.ca/posts/2018/03/06/node.js-too-many-open-files-and-ulimit/)

My error from npm installation:

```
$ npm -v 
6.7.0
$ node --version
v11.13.0
$ npm i -g mesg-cli

/root/.nvm/versions/node/v11.13.0/bin/mesg-cli -> /root/.nvm/versions/node/v11.13.0/lib/node_modules/mesg-cli/bin/run

> secp256k1@3.7.1 install /root/.nvm/versions/node/v11.13.0/lib/node_modules/mesg-cli/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

Error: EACCES: permission denied, scandir '/root/.nvm/versions/node/v11.13.0/lib/node_modules/mesg-cli/node_modules/secp256k1'
(node:22515) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'loaded' of undefined
    at exit (/usr/lib/node_modules/npm/lib/utils/error-handler.js:98:27)
    at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:216:3)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:78:20
    at cb (/usr/lib/node_modules/npm/lib/npm.js:225:22)
    at /usr/lib/node_modules/npm/lib/npm.js:263:24
    at /usr/lib/node_modules/npm/lib/config/core.js:83:7
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/npm/lib/config/core.js:82:13
    at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at /usr/lib/node_modules/npm/lib/config/core.js:112:20
(node:22515) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22515) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
TypeError: Cannot read property 'loaded' of undefined
    at process.<anonymous> (/usr/lib/node_modules/npm/lib/utils/error-handler.js:40:18)
    at process.emit (events.js:193:13)
/usr/lib/node_modules/npm/lib/utils/error-handler.js:98
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (/usr/lib/node_modules/npm/lib/utils/error-handler.js:98:27)
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:216:3)
    at process.emit (events.js:193:13)
    at process._fatalException (internal/process/execution.js:123:25)
Secp256k1 bindings compilation fail. Pure JS implementation will be used.

> ursa-optional@0.9.10 install /root/.nvm/versions/node/v11.13.0/lib/node_modules/mesg-cli/node_modules/ursa-optional
> node rebuild.js

internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v11.13.0/lib/node_modules/mesg-cli/node_modules/ursa-optional/rebuild.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa-optional@0.9.10 install: `node rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa-optional@0.9.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-19T06_03_22_560Z-debug.log
```

**Comment by antho1404** [comment]
This article might be useful https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by NicolasMahe** [comment]
I could install the cli after running:
```
npm config set user 0
npm config set unsafe-perm true
```
Solution found on https://github.com/jansmolders86/mediacenterjs/issues/191#issuecomment-317437604
